theme: jekyll-theme-minimal
logo: /img/logo_AME.png
title: "Tutoriels du Département AME, Université Gustave Eiffel"
description: "Tutoriels de support à la recherche et à l'ingénierie (communication, développement informatique, ...)"
markdown: kramdown